### ISSUE TITLE
Edit Ticket - status

### ISSUE THREAD

**Issue by SolvingCurves** [evereux/flicket#17]
In editing a ticket, the code in edit.py is initializing with the current status in the form but the edit form has no status field - so there's an error triggered.
*line 88 - edit.py: ticket.status_id = form.status.data*
I think you must either comment this line or add the status field in the edit form.

**Comment by evereux** [comment]
Hello, this was fixed in the 0.1.7 branch already along with other changes to that file. I'll push that to the master branch ASAP.

Thanks for the feedback.

**Comment by evereux** [comment]
This issue should be resolved now so I'll close this. If you still experience problems feel free to reopen.
