### ISSUE TITLE
Production settings are not so 'production ready'.

### ISSUE THREAD

**Issue by dustinwinski** [evereux/flicket#18]
I don't know really where to post this, but first off....
**I love this project.**
I work at a community college and because we're in a unique position we're only now starting to get our own infrastructure. This may definitely provide that! It looks very promising. 

My one big concern is that there really is no 'built-in' solution for making this production ready at the level I need it.... however I do have a suggestion.

I have launched several Flask web apps and we use the Cherrypy projects production webserver Cheroot. It's a simple import and the configuration looks very similar to Flask's dev server.

Would anyone be interested in or has any reservations of me providing a 'fix' for this?

**Comment by dustinwinski** [comment]
Cheroot will be over no problem if you would like to place Apache or Nginex in front of it. In fact, that's what I do.
At work i have Nginx terminate HTTPS for all my applications and have them reverse proxy to each specific application running at localhost.
I have already made the changes to my local repo and was extremely easy to implement. I can submit an actual pull request when I get the chance over the weekend so you can actually see what it's doing.
-------- Original message --------From: evereux <notifications@github.com> Date: 1/11/19  13:25  (GMT-05:00) To: evereux/flicket <flicket@noreply.github.com> Cc: Dustin Winski <dustinwinski@gmail.com>, Author <author@noreply.github.com> Subject: Re: [evereux/flicket] Production settings are not so 'production
  ready'. (#18) 
Hello,
Thanks very much for the feedback! I hope this can provide a helpful tool for you!
Whilst it's not clear in the current README file I never considered actually using python to serve the application in a production environment. I assumed a user would use something like Apache (which I'm more familiar with) or nginx. I'll change the wording in the README file so this is clear, it isn't at the moment.
I'll look to see if cheroot can be implemented without affecting the ability of serving the application with something like apache over the weekend. I'm not familiar with it but if it can be bundled within flicket and used as an option I see no problem.
Cheers

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/evereux/flicket","title":"evereux/flicket","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/evereux/flicket"}},"updates":{"snippets":[{"icon":"PERSON","message":"@evereux in #18: Hello,\r\n\r\nThanks very much for the feedback! I hope this can provide a helpful tool for you!\r\n\r\nWhilst it's not clear in the current README file I never considered actually using python to serve the application in a production environment. I assumed a user would use something like Apache (which I'm more familiar with) or nginx. I'll change the wording in the README file so this is clear, it isn't at the moment.\r\n\r\nI'll look to see if cheroot can be implemented without affecting the ability of serving the application with something like apache over the weekend. I'm not familiar with it but if it can be bundled within flicket and used as an option I see no problem.\r\n\r\nCheers"}],"action":{"name":"View Issue","url":"https://github.com/evereux/flicket/issues/18#issuecomment-453611058"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/evereux/flicket/issues/18#issuecomment-453611058",
"url": "https://github.com/evereux/flicket/issues/18#issuecomment-453611058",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by evereux** [comment]
Go for it! I'll take a look.

Thanks.

**Comment by dustinwinski** [comment]
Hi Evereux

So, while I'm a small time developer who uses Open Source software from here all the time... I've never actually contributed... how best do I do that?

Do I fork a copy of this repo under my own account on here and then make a pull request by using the "compare across forks" feature?

**Comment by evereux** [comment]
I'm not familiar with the process myself (I've only done this once myself) but that's the general idea I believe yes.

Give it a go. You won't break anything. If anything does break, it'll be my fault. :-)

**Comment by evereux** [comment]
I've updated the documentation / read me etc so that it's clear that python shouldn't be directly used for a production environment. I've also included instructions on how to install Apache for windows users. There's been no further action on this issue so closing ticket.
