### ISSUE TITLE
setup issue

### ISSUE THREAD

**Issue by Pechi77** [evereux/flicket#21]
Hi @evereux  I have cloned the file and created a new env, ran `pip install -r requirements.txt`.  I faced two errors.

1.
```
Collecting mimesis==2.1.0 (from -r requirements.txt (line 26))
  Using cached https://files.pythonhosted.org/packages/ce/e8/f7a590bfa26d654d139e124dafb178fbd1133e86cc6773f1d5c031250689/mimesis-2.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\manoj.sh\appdata\local\temp\pip-install-iamijm\mimesis\setup.py", line 105, in <module>
        with open('README.rst', 'r', encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
```

> I also tried replacing mimesis==2.1.0 to mimesis latest version.
this time. 

```
Collecting mimesis (from -r requirements.txt (line 26))
  Using cached https://files.pythonhosted.org/packages/fe/4f/2c636410653f79ceb41ee56e937adb1ff8c41d0cf649fc1df8796c1442d5/mimesis-3.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\manoj.sh\appdata\local\temp\pip-install-antvle\mimesis\setup.py", line 10, in <module>
        from mimesis import (
      File "mimesis\__init__.py", line 10, in <module>
        from mimesis.providers import *
      File "mimesis\providers\__init__.py", line 5, in <module>
        from mimesis.providers.base import BaseProvider, BaseDataProvider
      File "mimesis\providers\base.py", line 23
        def __init__(self, seed: Seed = None) -> None:
                               ^
    SyntaxError: invalid syntax

```

due to these errors I completely removed mimesis from my requirements.txt and ran. 

after installing requirements, I tried.
python setup.py install, 

then

```
ract[chat_embed] final\flicket>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from application import db, app
  File "D:\MANO\LEARNING\AI_PYTHON\CHATTERBOT\flask app eg[IMP]\flask-chatterbot -human_interact[chat_embed] final\flicket\application\__init__.py", line 16, in <module>
    from application.flicket_api_v2.views import bp_api_v2
ImportError: No module named flicket_api_v2.views

```

**Do you have any updated documentation for flicket to use. I see this flicket will help many people but people need a documentation to understand how it works. Thanks.**

**Comment by evereux** [comment]
Which version of python have you installed?

**Comment by evereux** [comment]
I have just installed the requirements.txt in a freshly cloned copy of Flicket using environments for both python 3.5 and 3.7. Both worked just fine. Are you using python 2.7? This version is not supported. Please see the README file.

> after installing requirements, I tried.
> python setup.py install,

You do not install Flicket like this. Please read the README on the front page: [https://github.com/evereux/flicket](https://github.com/evereux/flicket)

> **Do you have any updated documentation for flicket to use. I see this flicket will help many people but people need a documentation to understand how it works. Thanks.**

I'm working on better documentation when I can. In the meantime, see the README file.

**Comment by evereux** [comment]
Just for the hell of it I tried installing the requirements in a legacy python 2.7.16 environment. I got the same error as you have reported.

**Comment by Pechi77** [comment]
hi @evereux I am sorry, I did not notice that the new conda env created it with python 2.7. I will create 3x and try again. Thanks for your help.

**Comment by evereux** [comment]
You're welcome. I hope the installation goes smoothly now.

**Comment by Pechi77** [comment]
installation is completed, thanks but we faced another issue reported here #22 working on it.

**Comment by evereux** [comment]
That is a mysql database connection issue. Not an issue with Flicket as far as I can tell.
