### ISSUE TITLE
API Documentation Section is blank

### ISSUE THREAD

**Issue by loscil06** [evereux/flicket#28]
Self explanatory, see screenshot.
![image](https://user-images.githubusercontent.com/40837050/66057853-03058e80-e4ff-11e9-9b79-b17a9f357974.png)

**Comment by evereux** [comment]
I'm aware of the issue but I currently haven't been able to solve it. The API docs build fine from the source but Read the Docs doesn't.

Any suggested solutions would be great.

**Comment by evereux** [comment]
This is fixed now.

The problem was due to the `requirements-development.txt` file. Simply, this file should have all the production requirements PLUS the development requirements.

**Comment by loscil06** [comment]
Thanks a lot.

**Comment by evereux** [comment]
You're welcome.

Note that this is currently in the 0.2.1 branch only until it's merged to master: https://flicket.readthedocs.io/en/0.2.1/.

There have been no changes to the API to 0.2.1 though.
