### ISSUE TITLE
Creating a ticket makes the creator appear to be subscribed twice

### ISSUE THREAD

**Issue by loscil06** [evereux/flicket#29]
Steps: create new ticket > new ticket will have the creator name twice in subscriptions see:

![image](https://user-images.githubusercontent.com/40837050/66592818-6b85e880-eb5b-11e9-96ca-ae0d429e886f.png)

**Comment by evereux** [comment]
Hi Alan,

I'm pretty sure that's fixed in the released 0.2.0 version. I'll update it
shortly to make sure. Thanks for letting me know.

Paul

**Comment by evereux** [comment]
Yes, the version running on my server was a little out of date. This has now been rectified.

The github version does not have this issue.
