### ISSUE TITLE
Replying and Replying and close with file attached crashes

### ISSUE THREAD

**Issue by loscil06** [evereux/flicket#30]
I tried this in one of my created tickets, when replying and closing with a file attached (this case a 200bytes ish .txt file), the server will respond with the page error.
Actually, uploading a file in either way will cause the error.

**Comment by evereux** [comment]
This was a permissions problem with server. Not related to the application itself.

Please state that the error you are seeing is related to the "working" :) version I have provided access to in future.

**Comment by loscil06** [comment]
Alright thanks, will do in the future
