### ISSUE TITLE
Flicket session expiration

### ISSUE THREAD

**Issue by xdml** [evereux/flicket#36]
I do not like, that flicket session expires after 10 hours. I do a research and found, that it is because of `tokens` and the process how API tokens are generated in `def get_token(self, expires_in=36000)` and how staticmethod `check_token(token)` is implemented.

Inside property method `is_authenticated(self)` is:

```python
if self.check_token(self.token) is None:
    return False
```

This implementation results, that all sessions expire after 10 hours, at the same time API tokens expire.

In my opinion, it should be splitted, so API tokens have own expiration, and sessions own.

Based on how default class `UserMixin` is implemented, property `is_authenticated(self)` should always return `True`.

At the moment I am not pulling my changes, as I have to investigate, if it is safe to always return `True` and if `get_token()` is correctly called everytime user is going to use API (AJAX calls). I can imagine, that it can result in situation, the page will be loaded on one day and user will start fill form with API calls on another day. The token will be already expired, so autocompletion will not work, but after page reload it will work, so for end user it will result in bad user experience.

Maybe, API can be authenticated by tokens, base auth and sessions too. So API calls from AJAX will work with session authentication, API calls from external apps will work with base auth or token auth. But in this case, the question is, if 10 hour expiration is what external app will like.

Probably someone else already did investigation and can help me speed up work.

Another possibly related issue:

Remember Me function is not implemented according documentation of Flask-Login, but instead uses direct session data assignment `session['remember_me'] = form.remember_me.data`. Based on documentation `remember` argument of `login_user()` should be used (like `login_user(user, remember=True)`).

**Comment by xdml** [comment]
Thinking further. My suggestion is:

1. Allow session based authentication for API calls, so all AJAX calls from browser will be authenticated using sessions, and get rid of `Authorization: Bearer xxx` in calls made by browsers

2. Rework token based authentication, so any user can have multiple tokens, will explain below.

My opinion about API authentication and how it should work:

I think user can create many tokens, so each external application/script will have unique token, so user can easily revoke access to specific application/script. Similar to keys (or application passwords) Google uses to bypass two factor authentication (eg. for IMAP).

So remove `token` and `token_expiration` from `FlicketUser` model and create new model, let say `FlicketUserToken`, where will be relation to `FlicketUser` and have `token`, `token_expiration` and `note` and prepare configuration view, where user is able to create new tokens, set expiration and notes. User will be allowed to delete tokens. In my opinion, expiration should be set in a way of explicit time, timedelta for inactivity and none, if the token should never expire.

**Comment by evereux** [comment]
> Another possibly related issue:
> 
> Remember Me function is not implemented according documentation of Flask-Login, but instead uses direct session data assignment `session['remember_me'] = form.remember_me.data`. Based on documentation `remember` argument of `login_user()` should be used (like `login_user(user, remember=True)`).

I have made that change.

I'm still trying to digest the rest.

**Comment by evereux** [comment]
> Allow session based authentication for API calls, so all AJAX calls from browser will be authenticated using sessions, and get rid of Authorization: Bearer xxx in calls made by browsers

We have `flicket_bp` and `bp_api`. These should be able to run to run independently of each other on different servers. So in this case the `bp_api` will not have access to the main application session information. So, the only way to validate the request is to use some form of token based authentication, no?

> I do not like, that flicket session expires after 10 hours. I do a research and found, that it is because of tokens and the process how API tokens are generated in def get_token(self, expires_in=36000) and how staticmethod check_token(token) is implemented.

Why can't we refresh the token before page load if the user is remembered / authenticated? Nice and simple.

**Comment by xdml** [comment]
> We have `flicket_bp` and `bp_api`. These should be able to run to run independently of each other on different servers. So in this case the `bp_api` will not have access to the main application session information. So, the only way to validate the request is to use some form of token based authentication, no?

My first focus was, where the session data are stored on the server and discovered, that Flask-Login uses client side store. All information are stored in cookies and everything is signed with cryptography. So if all servers have the access to the same secret used for cryptography signing, there should not be problem with it and it should work. Not sure, why it is designed like it, but your point about backend servers and balancing traffic between them, is perfect example, that if the servers have access to the same signing secret, than it will work out of the box without difficult sharing configuration or storing sessions in database.

If you check your cookies, you will see, that all data stored in sessions are send to the browser in `Set-Cookie` header.

> Why can't we refresh the token before page load if the user is remembered / authenticated? Nice and simple.

Yes, you are right, it is possible, but:

- user will not be logged out, but token will be expired, so as I described above:
  - on one day user leave computer on a some form, where API calls are executed to backend
  - after 10 hours user start to fill form, and autocompletation is not working, as API token is expired
  - if user, reloads that page, the autocompletation starts to work (I mark this as bad user experience, as the user without knowledge about the code will not understand why it is happening)
- in my opinion it is useless action to refresh token on every page load resulting in many database updates and commits

And from my point of view, it is not necessary to refresh token on every page load. Much nicer and simpler will be, if `is_authenticated(self)` always returns `True`.

I probably do not fully understand, for what the API is created. I expected, that it is more for external application and scripts than for frontend JavaScript and if it is the case, than I really do not understand, why token expiration is implemented and why user is not allowed to create unique tokens per external application or script.

You know, noone knows what can happen. For example I will set my scripts on some server and if the server is compromised I have to revoke access to the flicket, but it does not neccessary mean, that I have to revoke all application tokens, just the one on the compromised server. So why not to have unique tokens for my applications or scripts? In my opinion it is good security practice to have unique tokens per application/script.

**Comment by evereux** [comment]
> in my opinion it is useless action to refresh token on every page load resulting in many database updates and commits

Only refresh token if it is expired and the user is authenticated.

I need to read up more on this subject. I kind of understand what you're getting at but I don't see the point of over complicating things.

**Comment by evereux** [comment]
So I've updated 0.2.1 now so that if the users token is expired a new token is issued (if they're authenticated).

I've done some reading and having the API using sessions for authentication is deemed bad practise and it doesn't sit right with me either. So that's not going to happen.

This is a simple ticket application and I really don't see the need for multiple tokens. I'm going to leave this ticket open for now in case someone can explain to me why using multiple tokens for this application is a good idea. 

I'm still unconvinced but willing to be shown otherwise.

**Comment by xdml** [comment]
Multiple tokens: security.

The best practice is not to share keys. So if user has multiple application/scripts, each application/script should use own key. So if user set some application to work with API and later user lost the access to that application, then user has to revoke the access to that application and best is to revoke only single key. It is very similar to Certificates and/or SSH keys, preshared IPSec keys etc. Even if the topology is build by the one admin, each component should use unique key.

But it does not make sense, if there is key expiration, as how you would update key regularly? At the moment it is usable only from frontend, so user has minimal options to use API from own scripts or own applications...

Thank you very much to change property `is_authenticated` to default one, so it always returns `True` as it is expected by Flask-Login.

**Comment by xdml** [comment]
> I've done some reading and having the API using sessions for authentication is deemed bad practise and it doesn't sit right with me either. So that's not going to happen.

Can you post your readings, I really do not understand it. The question is more about how the API is used and what best fit the usega. In case of flicket API, the frontend (browser) is using it, it is more like JavaScript application requests, than access from 3rd party. In contrast to 3rd party access, where session is unknown for the requester.

**Comment by evereux** [comment]
Any scripts should start with the user getting the API key.

https://flicket.readthedocs.io/en/0.2.1/api.html#get-token

**Comment by evereux** [comment]
https://restfulapi.net/

> Stateless – Each request from client to server must contain all of the information necessary to understand the request, and cannot take advantage of any stored context on the server. Session state is therefore kept entirely on the client.

**Comment by xdml** [comment]
OK, now it makes sense to have token expiration implemented. But still I personally tend to have multiple tokens against multiple clients, similarly to sessions.

At the moment I see it is solved and no more work is required.
