### ISSUE TITLE
UI sorting

### ISSUE THREAD

**Issue by xdml** [evereux/flicket#37]
Originally the ticket list was a table with headers where sorting had been implemented by adding clickable table headers.

After the UI changed, now there is one row with headers, but tickets itself are formatted in blocks instead table rows:

![obrazek](https://user-images.githubusercontent.com/1033684/69004721-4a61a600-0918-11ea-991e-b42f7d32189a.png)

Personally I think it is not intuitive and may confuse lot of users.

So, probably better will be to use `<select>` instead, like:

![obrazek](https://user-images.githubusercontent.com/1033684/69004763-b6440e80-0918-11ea-930f-c5751ab18b6d.png)

OR tabs, like:

![obrazek](https://user-images.githubusercontent.com/1033684/69004771-d1af1980-0918-11ea-80a7-bc4a39800046.png)

I personally like tabs more, but we will be limited with space, so for many sorting options `<select>` will be better choice.

**Comment by evereux** [comment]
I like it. Agreed.

I had planned on the same thing as I thought the sort bar took up too much 
space.

I can do that unless it's something you'd like to do.

**Comment by xdml** [comment]
My preference is to more focus on backend as to frontend, as I have minimal experience with UI design.

**Comment by evereux** [comment]
Same for me.

**Comment by xdml** [comment]
I'll pick this one. My suggestion is to do it like `<select>` on the right side of page on the same "row" as paginator at top.

**Comment by evereux** [comment]
Sounds good. I was going to add it to the search form but this is better.

**Comment by xdml** [comment]
I think this can be closed now.
