### ISSUE TITLE
Issues with Snowflake as Database

### ISSUE THREAD

**Issue by kirkholmes** [evereux/flicket#49]
I'm trying ti get your program up and running using Snowflake as the database and using the snowflake SQL-Alchemy connector(https://docs.snowflake.net/manuals/user-guide/sqlalchemy.html)

A couple of things I'm debugging in the program in case other people have similar issues. Snowflake does not support indexes so I edited out any lines with op.create_index in the migrations before source code control migration. I also edited the flicket_models and flicket_user files and removed index=True.

I also am not running into a new issue. It appears that SQLAlchemy only supports JSON in SQL in only a handful of databases (https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.JSON) not in snowflake. So you may want to use something more standard instead of JSON in the migration code. I came across this that suggests using text? https://www.reddit.com/r/flask/comments/7vxfcp/ask_flask_error_using_json_with_sqlalchemy/ Not sure what the right solution is to modify the migration script(s) to get this bad boy up and running but any help would be appreciated!

I've also reached out to the developers of the snowflake connector as well :)

**Comment by evereux** [comment]
I have no plans to support Snowflake. I'm closing this as there has been no futher discourse regarding using snowflake as a database.
