### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by NT3R117** [evereux/flicket#50]
Hello,

I have an invalid syntax error executing the command : "python(3) manage.py db upgrade" while installing the 0.2.2 version

Any idea ?

Thanks for your support :)

![Error](https://user-images.githubusercontent.com/61501206/75340783-6c61b180-5893-11ea-9d5f-b33a5a95d967.png)

**Comment by evereux** [comment]
Hello,

I've just cloned the master git branch and managed to run the set up just fine.

Can you provide more information about the steps you took until you got to this point? Did you create a virtual environment?

**Comment by NT3R117** [comment]
Hi,

Sorry for the late answer, yes it was a problem of virtual environment, it is solved now.

Thanks for your support :)

**Comment by evereux** [comment]
Cool. Glad you got it sorted. :-)
