### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by MMartin09** [evereux/flicket#59]
I am not able to run the upgrade database (or another command) due to the error `ImportError: cannot import name 'escape' from 'jinja2' `. 

I am using Python 3.9

**Comment by js-on** [comment]
Same here. Wanted to create a docker image for Flicket+SQL, but stumbled across this issue.
This is probably related to the following SO post: https://stackoverflow.com/a/71721006

Enforce the old jinja version in the requirements.txt file to get rid of the issue, but this is not the best solution.
Meanwhile I'll create a pull request for this and hope that it gets merged.

**Comment by evereux** [comment]
I have made updates that fix this issue in the [0.30](https://github.com/evereux/flicket/tree/0.3.0) branch.

I'll probably release later this week.

**Comment by evereux** [comment]
0.3.0 has now been pushed to the master branch and released.
