### ISSUE TITLE
paginate not working with flask-SQLAlchemy 3.0

### ISSUE THREAD

**Issue by abarkett** [evereux/flicket#62]
As of Flask-SQLAlchemy 3.0, all arguments to paginate are keyword-only.

File "application/flicket_admin/views/view_admin.py", line 85, in users
users = users.paginate(page, app.config['posts_per_page'])
TypeError: paginate() takes 1 positional argument but 3 were given

simply adding "page=" and "per_page=" keywords fixes this.  There are several calls to paginate in different files with the same issue.

**Comment by evereux** [comment]
Thanks for reporting this. I'll get this change implemented in the coming days.

**Comment by evereux** [comment]
When installing from fresh and using the requirements.txt file I don't end up with flask-sqlalchemy v3.0.

Did you manually install a later version? Was there a feature you wanted in v3.0 or a security issue?

**Comment by evereux** [comment]
Just had a thought ... I need to test this is python 3.10 too. The above I did with python 3.9. Perhaps python 3.10 will behave differently? I'll check that tomorrow.

**Comment by evereux** [comment]
I've fixed the sqlalchemy version in the requirements.txt file now.
