### ISSUE TITLE
plotly version in requirements.txt causes error

### ISSUE THREAD

**Issue by abarkett** [evereux/flicket#63]
Updating version in requirements.txt to 5.11 seems to work with light testing done.

**Comment by evereux** [comment]
Thanks for reporting this. I'll get this change implemented in the coming days.

**Comment by evereux** [comment]
I've just installed a fresh version from the requirements. I ended up with 5.10.1 and didn't get any errors. Considering your issue #62 were there other changes you have made?

**Comment by joma-s** [comment]
This might have to do with the Python version. I'm running on Python 3.10.7 and got the same error. I just updated my requirements to the latest version of plotly (currently 5.13.1) and it worked.

**Comment by evereux** [comment]
Thanks for reporting this. I have now updated the dependencies and minimum python version.
