### ISSUE TITLE
Incompatible SQLAlchemy version

### ISSUE THREAD

**Issue by joma-s** [evereux/flicket#65]
Hi evereux, hope you're well..

I've installed a fresh install and had some issue with the dependencies.
By installing with the requirements.txt, it installed flask-migrate 3.1.0, which has Flask-SQLAlchemy as a dependency (however I think it doesn't specify a version, and installed version 3.0.3) which then has SQLAlchemy as a dependency (which probably doesn't specify a version), and it ended up installing the latest version (SQLAlchemy 2.0.4). However this caused some issue with columns when running **flask db update** and was not able to run it at all.

I ended up downgrading Flask-SQLAlchemy to v2.5.1 and SQLAlchemy to v1.3.24 and now everything seems to run ok.

So it might be a good idea to update the requirements.txt and include these versions or the ones you are using to help newcomers?

Many thanks!

**Comment by WayneMercer** [comment]
joma-s - thanks for finding this (and reporting it!). I was at my wit's end trying to get this to work. 

I also found that pip can't find plotly at v5.10.1, but 5.14.1 does seem to work fine.

**Comment by evereux** [comment]
Thanks for reporting this. I have now updated the dependencies and minimum python version.
