### ISSUE TITLE
Download results as a csv file  .    gives as a result KeyError KeyError: 'created_id'

### ISSUE THREAD

**Issue by Silvio1975** [evereux/flicket#69]
when I click on Download results as csv file   gives as a result KeyError
KeyError: 'created_id'

Traceback (last most recent call)
"C: Python311 Lib site-packages flask app.py" file, line 2548, in
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C: Python311 Lib site-packages flask app.py", line 2528, in wsgi_app
response = self-sufficiency(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
File "C: Python311 Lib site-packages flask app.py", line 2525, in wsgi_app
response = full shipping request ()  

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Thank you very much to those who can help me

**Comment by evereux** [comment]
I get the same issue here. I'll take a look at this tomorrow, should be a simple fix.

**Comment by evereux** [comment]
New version has now been released so I'm now closing this ticket.
