### ISSUE TITLE
Setup question - manage.py

### ISSUE THREAD

**Issue by Stone2080** [evereux/flicket#74]
Hi
Master branch
From documentation - step 5
5. Upgrade the database using manage.py from the command line::

    flask db upgrade

Where can I find manage.py ?

Thanks

**Comment by evereux** [comment]
It's been awhile but I think that statement is only applicable to older versions and needs updating.

You should be able to just run `flask db upgrade`.

**Comment by evereux** [comment]
I have just done a fresh installation using python 3.12 and it is working fine.

Did you follow the steps and install the requirements per the requirements.txt? What are the results of pip freeze?

**Comment by Stone2080** [comment]
You are right - it was a misconfiguration on my side.
Thank you
