### ISSUE TITLE
SAWarning: implicitly coercing SELECT object to scalar subquery

### ISSUE THREAD

**Issue by jignesh03** [evereux/flicket#75]
SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
  user_def = db.deferred(db.select(FlicketUser.name).where(FlicketUser.id == user_id))

using on windows 
database sqllite

**Comment by evereux** [comment]
I'm aware of this is warning. Is it causing you an issue?

Just haven't spent time yet figuring out how to rewrite that query.
