### ISSUE TITLE
Using the bin/delete icon on a department produces an error

### ISSUE THREAD

**Issue by McSpidey** [evereux/flicket#8]
The error is: "werkzeug.routing.BuildError: Could not build url for endpoint 'departments'"

**Comment by McSpidey** [comment]
For anyone else that has this the fix is to update the return redirect lines in the "application\flicket\views\delete.py" file's "delete_department" function
from
return redirect(url_for('departments'))
to
return redirect(url_for('flicket_bp.departments'))

**Comment by evereux** [comment]
Thanks for the report and apologies for the slow response!

Merged request with master and added change to 0.1.4a.
